name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.os == 'windows-latest' && 'x86_64-pc-windows-gnu' || matrix.os == 'macos-latest' && 'x86_64-apple-darwin' || 'x86_64-unknown-linux-gnu' }}

    - name: Build
      run: cargo build --release

    - name: Upload binary
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os == 'windows-latest' && 'your_binary_name-windows-amd64.exe' || matrix.os == 'macos-latest' && 'your_binary_name-macos-amd64' || 'your_binary_name-linux-amd64' }}
        path: target/release/your_binary_name${{ matrix.os == 'windows-latest' && '.exe' || '' }}
